
import json
import csv
import os
import sys
from datetime import datetime

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RTS Benchmark Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; color: #333; }}
        .container {{ max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        h1 {{ border-bottom: 2px solid #eee; padding-bottom: 10px; color: #2c3e50; }}
        .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }}
        .card {{ background: #f8f9fa; padding: 15px; border-radius: 6px; border-left: 4px solid #3498db; }}
        .card.danger {{ border-left-color: #e74c3c; }}
        .card.success {{ border-left-color: #2ecc71; }}
        .card h3 {{ margin: 0 0 5px 0; font-size: 14px; color: #7f8c8d; text-transform: uppercase; }}
        .card .value {{ font-size: 24px; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #f8f9fa; }}
        .footer {{ margin-top: 40px; font-size: 12px; color: #7f8c8d; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>RTS Benchmark Result</h1>
        <p><strong>Date:</strong> {date}</p>
        
        <h2>Performance Summary</h2>
        <div class="summary-grid">
            <div class="card">
                <h3>Throughput</h3>
                <div class="value">{throughput} msg/s</div>
            </div>
            <div class="card {latency_class}">
                <h3>Avg Latency (P50)</h3>
                <div class="value">{p50} ms</div>
            </div>
            <div class="card {jitter_class}">
                <h3>Jitter</h3>
                <div class="value">{jitter} ms</div>
            </div>
             <div class="card {loss_class}">
                <h3>Packet Loss</h3>
                <div class="value">{loss}%</div>
            </div>
        </div>

        <h2>Detailed Metrics</h2>
        <table>
            <tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Alarm Latency (P99)</td><td>{alarm_p99} ms</td></tr>
            <tr><td>Telemetry Latency (P99)</td><td>{telemetry_p99} ms</td></tr>
            <tr><td>Database Write Time</td><td>{db_time} ms</td></tr>
            <tr><td>Total Messages</td><td>{total_msg}</td></tr>
            <tr><td>Duration</td><td>{duration} s</td></tr>
        </table>

        <div class="footer">
            Generated by RTS WebServer-v2 Report Tool
        </div>
    </div>
</body>
</html>
"""

def generate_report(results_dir):
    json_path = os.path.join(results_dir, "summary.json")
    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found.")
        return

    with open(json_path, 'r') as f:
        data = json.load(f)

    # Determine classes for coloring
    latency_class = "success" if data.get('alarm_p50_ms', 0) < 150 else "danger"
    loss_val = data.get('telemetry_deadline_miss_rate', 0) * 100
    loss_class = "success" if loss_val < 5 else "danger"

    html = HTML_TEMPLATE.format(
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        throughput=data.get('throughput_msg_s', 0),
        p50=data.get('alarm_p50_ms', 0),
        jitter=round(data.get('alarm_jitter_ms', 0), 2),
        latency_class=latency_class,
        jitter_class="card",
        loss_class=loss_class,
        loss=round(loss_val, 2),
        alarm_p99=data.get('alarm_p99_ms', 0),
        telemetry_p99=data.get('telemetry_p99_ms', 0),
        db_time=data.get('db_time_p95_ms', 0),
        total_msg=int(data.get('throughput_msg_s', 0) * data.get('duration_s', 1)),
        duration=data.get('duration_s', 0)
    )

    output_path = os.path.join(results_dir, "report.html")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)
    
    print(f"Report generated: {output_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_report.py <results_dir>")
        sys.exit(1)
    generate_report(sys.argv[1])
